// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countCards = `-- name: CountCards :one
SELECT COUNT(*) FROM cards
`

func (q *Queries) CountCards(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCards)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCard = `-- name: CreateCard :one
INSERT INTO cards (card_name, card_kind, card_icon_url, rarity, card_detail)
VALUES ($1, $2, $3, $4, $5)
RETURNING card_id
`

type CreateCardParams struct {
	CardName    string
	CardKind    int16
	CardIconUrl sql.NullString
	Rarity      sql.NullString
	CardDetail  sql.NullString
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createCard,
		arg.CardName,
		arg.CardKind,
		arg.CardIconUrl,
		arg.Rarity,
		arg.CardDetail,
	)
	var card_id int32
	err := row.Scan(&card_id)
	return card_id, err
}

const createCharacter = `-- name: CreateCharacter :exec
INSERT INTO characters (
    character_id, card_id, hp, atk, tech,
    init_hp, init_atk, init_tech,
    max_hp, max_atk, max_tech, special_type
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateCharacterParams struct {
	CharacterID uuid.UUID
	CardID      int32
	Hp          int32
	Atk         int32
	Tech        int32
	InitHp      int32
	InitAtk     int32
	InitTech    int32
	MaxHp       int32
	MaxAtk      int32
	MaxTech     int32
	SpecialType sql.NullString
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) error {
	_, err := q.db.ExecContext(ctx, createCharacter,
		arg.CharacterID,
		arg.CardID,
		arg.Hp,
		arg.Atk,
		arg.Tech,
		arg.InitHp,
		arg.InitAtk,
		arg.InitTech,
		arg.MaxHp,
		arg.MaxAtk,
		arg.MaxTech,
		arg.SpecialType,
	)
	return err
}

const createEquipment = `-- name: CreateEquipment :exec
INSERT INTO equipments (
    equipment_id, card_id, bonus_hp, bonus_atk, bonus_tech,
    init_bonus_hp, init_bonus_atk, init_bonus_tech,
    max_bonus_hp, max_bonus_atk, max_bonus_tech, buff_effect
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateEquipmentParams struct {
	EquipmentID   uuid.UUID
	CardID        int32
	BonusHp       int32
	BonusAtk      int32
	BonusTech     int32
	InitBonusHp   int32
	InitBonusAtk  int32
	InitBonusTech int32
	MaxBonusHp    int32
	MaxBonusAtk   int32
	MaxBonusTech  int32
	BuffEffect    sql.NullString
}

func (q *Queries) CreateEquipment(ctx context.Context, arg CreateEquipmentParams) error {
	_, err := q.db.ExecContext(ctx, createEquipment,
		arg.EquipmentID,
		arg.CardID,
		arg.BonusHp,
		arg.BonusAtk,
		arg.BonusTech,
		arg.InitBonusHp,
		arg.InitBonusAtk,
		arg.InitBonusTech,
		arg.MaxBonusHp,
		arg.MaxBonusAtk,
		arg.MaxBonusTech,
		arg.BuffEffect,
	)
	return err
}

const getAllCharacters = `-- name: GetAllCharacters :many
SELECT character_id, card_id, hp, atk, tech, init_hp, init_atk, init_tech, max_hp, max_atk, max_tech, special_type FROM characters
`

func (q *Queries) GetAllCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, getAllCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.CharacterID,
			&i.CardID,
			&i.Hp,
			&i.Atk,
			&i.Tech,
			&i.InitHp,
			&i.InitAtk,
			&i.InitTech,
			&i.MaxHp,
			&i.MaxAtk,
			&i.MaxTech,
			&i.SpecialType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCharactersWithCard = `-- name: GetAllCharactersWithCard :many
SELECT ch.character_id, c.card_id, c.card_name, c.card_icon_url, c.rarity,
  ch.hp, ch.atk, ch.tech, ch.init_hp, ch.init_atk, ch.init_tech,
  ch.max_hp, ch.max_atk, ch.max_tech, ch.special_type
FROM characters ch JOIN cards c ON c.card_id = ch.card_id
`

type GetAllCharactersWithCardRow struct {
	CharacterID uuid.UUID
	CardID      int32
	CardName    string
	CardIconUrl sql.NullString
	Rarity      sql.NullString
	Hp          int32
	Atk         int32
	Tech        int32
	InitHp      int32
	InitAtk     int32
	InitTech    int32
	MaxHp       int32
	MaxAtk      int32
	MaxTech     int32
	SpecialType sql.NullString
}

func (q *Queries) GetAllCharactersWithCard(ctx context.Context) ([]GetAllCharactersWithCardRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCharactersWithCard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCharactersWithCardRow
	for rows.Next() {
		var i GetAllCharactersWithCardRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.CardID,
			&i.CardName,
			&i.CardIconUrl,
			&i.Rarity,
			&i.Hp,
			&i.Atk,
			&i.Tech,
			&i.InitHp,
			&i.InitAtk,
			&i.InitTech,
			&i.MaxHp,
			&i.MaxAtk,
			&i.MaxTech,
			&i.SpecialType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllEquipments = `-- name: GetAllEquipments :many
SELECT equipment_id, card_id, bonus_hp, bonus_atk, bonus_tech, init_bonus_hp, init_bonus_atk, init_bonus_tech, max_bonus_hp, max_bonus_atk, max_bonus_tech, buff_effect FROM equipments
`

func (q *Queries) GetAllEquipments(ctx context.Context) ([]Equipment, error) {
	rows, err := q.db.QueryContext(ctx, getAllEquipments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipment
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.EquipmentID,
			&i.CardID,
			&i.BonusHp,
			&i.BonusAtk,
			&i.BonusTech,
			&i.InitBonusHp,
			&i.InitBonusAtk,
			&i.InitBonusTech,
			&i.MaxBonusHp,
			&i.MaxBonusAtk,
			&i.MaxBonusTech,
			&i.BuffEffect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllEquipmentsWithCard = `-- name: GetAllEquipmentsWithCard :many
SELECT e.equipment_id, c.card_id, c.card_name, c.card_icon_url, c.rarity,
  e.bonus_hp, e.bonus_atk, e.bonus_tech, e.init_bonus_hp, e.init_bonus_atk, e.init_bonus_tech,
  e.max_bonus_hp, e.max_bonus_atk, e.max_bonus_tech, e.buff_effect
FROM equipments e JOIN cards c ON c.card_id = e.card_id
`

type GetAllEquipmentsWithCardRow struct {
	EquipmentID   uuid.UUID
	CardID        int32
	CardName      string
	CardIconUrl   sql.NullString
	Rarity        sql.NullString
	BonusHp       int32
	BonusAtk      int32
	BonusTech     int32
	InitBonusHp   int32
	InitBonusAtk  int32
	InitBonusTech int32
	MaxBonusHp    int32
	MaxBonusAtk   int32
	MaxBonusTech  int32
	BuffEffect    sql.NullString
}

func (q *Queries) GetAllEquipmentsWithCard(ctx context.Context) ([]GetAllEquipmentsWithCardRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllEquipmentsWithCard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEquipmentsWithCardRow
	for rows.Next() {
		var i GetAllEquipmentsWithCardRow
		if err := rows.Scan(
			&i.EquipmentID,
			&i.CardID,
			&i.CardName,
			&i.CardIconUrl,
			&i.Rarity,
			&i.BonusHp,
			&i.BonusAtk,
			&i.BonusTech,
			&i.InitBonusHp,
			&i.InitBonusAtk,
			&i.InitBonusTech,
			&i.MaxBonusHp,
			&i.MaxBonusAtk,
			&i.MaxBonusTech,
			&i.BuffEffect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacter = `-- name: GetCharacter :one
SELECT character_id, card_id, hp, atk, tech, init_hp, init_atk, init_tech, max_hp, max_atk, max_tech, special_type FROM characters WHERE character_id=$1 LIMIT 1
`

func (q *Queries) GetCharacter(ctx context.Context, characterID uuid.UUID) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, characterID)
	var i Character
	err := row.Scan(
		&i.CharacterID,
		&i.CardID,
		&i.Hp,
		&i.Atk,
		&i.Tech,
		&i.InitHp,
		&i.InitAtk,
		&i.InitTech,
		&i.MaxHp,
		&i.MaxAtk,
		&i.MaxTech,
		&i.SpecialType,
	)
	return i, err
}

const getCharacterWithCard = `-- name: GetCharacterWithCard :one
SELECT ch.character_id, c.card_id, c.card_name, c.card_icon_url, c.rarity,
  ch.hp, ch.atk, ch.tech, ch.init_hp, ch.init_atk, ch.init_tech,
  ch.max_hp, ch.max_atk, ch.max_tech, ch.special_type
FROM characters ch JOIN cards c ON c.card_id = ch.card_id
WHERE ch.character_id = $1 LIMIT 1
`

type GetCharacterWithCardRow struct {
	CharacterID uuid.UUID
	CardID      int32
	CardName    string
	CardIconUrl sql.NullString
	Rarity      sql.NullString
	Hp          int32
	Atk         int32
	Tech        int32
	InitHp      int32
	InitAtk     int32
	InitTech    int32
	MaxHp       int32
	MaxAtk      int32
	MaxTech     int32
	SpecialType sql.NullString
}

func (q *Queries) GetCharacterWithCard(ctx context.Context, characterID uuid.UUID) (GetCharacterWithCardRow, error) {
	row := q.db.QueryRowContext(ctx, getCharacterWithCard, characterID)
	var i GetCharacterWithCardRow
	err := row.Scan(
		&i.CharacterID,
		&i.CardID,
		&i.CardName,
		&i.CardIconUrl,
		&i.Rarity,
		&i.Hp,
		&i.Atk,
		&i.Tech,
		&i.InitHp,
		&i.InitAtk,
		&i.InitTech,
		&i.MaxHp,
		&i.MaxAtk,
		&i.MaxTech,
		&i.SpecialType,
	)
	return i, err
}

const getEquipment = `-- name: GetEquipment :one
SELECT equipment_id, card_id, bonus_hp, bonus_atk, bonus_tech, init_bonus_hp, init_bonus_atk, init_bonus_tech, max_bonus_hp, max_bonus_atk, max_bonus_tech, buff_effect FROM equipments WHERE equipment_id=$1 LIMIT 1
`

func (q *Queries) GetEquipment(ctx context.Context, equipmentID uuid.UUID) (Equipment, error) {
	row := q.db.QueryRowContext(ctx, getEquipment, equipmentID)
	var i Equipment
	err := row.Scan(
		&i.EquipmentID,
		&i.CardID,
		&i.BonusHp,
		&i.BonusAtk,
		&i.BonusTech,
		&i.InitBonusHp,
		&i.InitBonusAtk,
		&i.InitBonusTech,
		&i.MaxBonusHp,
		&i.MaxBonusAtk,
		&i.MaxBonusTech,
		&i.BuffEffect,
	)
	return i, err
}

const getEquipmentWithCard = `-- name: GetEquipmentWithCard :one
SELECT e.equipment_id, c.card_id, c.card_name, c.card_icon_url, c.rarity,
  e.bonus_hp, e.bonus_atk, e.bonus_tech, e.init_bonus_hp, e.init_bonus_atk, e.init_bonus_tech,
  e.max_bonus_hp, e.max_bonus_atk, e.max_bonus_tech, e.buff_effect
FROM equipments e JOIN cards c ON c.card_id = e.card_id
WHERE e.equipment_id = $1 LIMIT 1
`

type GetEquipmentWithCardRow struct {
	EquipmentID   uuid.UUID
	CardID        int32
	CardName      string
	CardIconUrl   sql.NullString
	Rarity        sql.NullString
	BonusHp       int32
	BonusAtk      int32
	BonusTech     int32
	InitBonusHp   int32
	InitBonusAtk  int32
	InitBonusTech int32
	MaxBonusHp    int32
	MaxBonusAtk   int32
	MaxBonusTech  int32
	BuffEffect    sql.NullString
}

func (q *Queries) GetEquipmentWithCard(ctx context.Context, equipmentID uuid.UUID) (GetEquipmentWithCardRow, error) {
	row := q.db.QueryRowContext(ctx, getEquipmentWithCard, equipmentID)
	var i GetEquipmentWithCardRow
	err := row.Scan(
		&i.EquipmentID,
		&i.CardID,
		&i.CardName,
		&i.CardIconUrl,
		&i.Rarity,
		&i.BonusHp,
		&i.BonusAtk,
		&i.BonusTech,
		&i.InitBonusHp,
		&i.InitBonusAtk,
		&i.InitBonusTech,
		&i.MaxBonusHp,
		&i.MaxBonusAtk,
		&i.MaxBonusTech,
		&i.BuffEffect,
	)
	return i, err
}
