// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getAllCharacters = `-- name: GetAllCharacters :many
SELECT character_id, card_id, hp, atk, tech, init_hp, init_atk, init_tech, max_hp, max_atk, max_tech, special_type FROM characters
`

func (q *Queries) GetAllCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, getAllCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.CharacterID,
			&i.CardID,
			&i.Hp,
			&i.Atk,
			&i.Tech,
			&i.InitHp,
			&i.InitAtk,
			&i.InitTech,
			&i.MaxHp,
			&i.MaxAtk,
			&i.MaxTech,
			&i.SpecialType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllEquipments = `-- name: GetAllEquipments :many
SELECT equipment_id, card_id, bonus_hp, bonus_atk, bonus_tech, init_bonus_hp, init_bonus_atk, init_bonus_tech, max_bonus_hp, max_bonus_atk, max_bonus_tech, buff_effect FROM equipments
`

func (q *Queries) GetAllEquipments(ctx context.Context) ([]Equipment, error) {
	rows, err := q.db.QueryContext(ctx, getAllEquipments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipment
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.EquipmentID,
			&i.CardID,
			&i.BonusHp,
			&i.BonusAtk,
			&i.BonusTech,
			&i.InitBonusHp,
			&i.InitBonusAtk,
			&i.InitBonusTech,
			&i.MaxBonusHp,
			&i.MaxBonusAtk,
			&i.MaxBonusTech,
			&i.BuffEffect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCharacter = `-- name: GetCharacter :one
SELECT character_id, card_id, hp, atk, tech, init_hp, init_atk, init_tech, max_hp, max_atk, max_tech, special_type FROM characters WHERE character_id=$1 LiMIT 1
`

func (q *Queries) GetCharacter(ctx context.Context, characterID uuid.UUID) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, characterID)
	var i Character
	err := row.Scan(
		&i.CharacterID,
		&i.CardID,
		&i.Hp,
		&i.Atk,
		&i.Tech,
		&i.InitHp,
		&i.InitAtk,
		&i.InitTech,
		&i.MaxHp,
		&i.MaxAtk,
		&i.MaxTech,
		&i.SpecialType,
	)
	return i, err
}

const getEquipment = `-- name: GetEquipment :one
SELECT equipment_id, card_id, bonus_hp, bonus_atk, bonus_tech, init_bonus_hp, init_bonus_atk, init_bonus_tech, max_bonus_hp, max_bonus_atk, max_bonus_tech, buff_effect FROM equipments WHERE equipment_id=$1 LIMIT 1
`

func (q *Queries) GetEquipment(ctx context.Context, equipmentID uuid.UUID) (Equipment, error) {
	row := q.db.QueryRowContext(ctx, getEquipment, equipmentID)
	var i Equipment
	err := row.Scan(
		&i.EquipmentID,
		&i.CardID,
		&i.BonusHp,
		&i.BonusAtk,
		&i.BonusTech,
		&i.InitBonusHp,
		&i.InitBonusAtk,
		&i.InitBonusTech,
		&i.MaxBonusHp,
		&i.MaxBonusAtk,
		&i.MaxBonusTech,
		&i.BuffEffect,
	)
	return i, err
}
