// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enhancement.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getCardKindByInstanceID = `-- name: GetCardKindByInstanceID :one
SELECT c.card_id, c.card_kind, c.rarity
FROM user_cards uc
JOIN cards c ON c.card_id = uc.card_id
WHERE uc.instance_id = $1 AND uc.user_id = $2
`

type GetCardKindByInstanceIDParams struct {
	InstanceID uuid.UUID
	UserID     uuid.UUID
}

type GetCardKindByInstanceIDRow struct {
	CardID   int32
	CardKind int16
	Rarity   sql.NullString
}

func (q *Queries) GetCardKindByInstanceID(ctx context.Context, arg GetCardKindByInstanceIDParams) (GetCardKindByInstanceIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCardKindByInstanceID, arg.InstanceID, arg.UserID)
	var i GetCardKindByInstanceIDRow
	err := row.Scan(&i.CardID, &i.CardKind, &i.Rarity)
	return i, err
}

const getCharacterByCardID = `-- name: GetCharacterByCardID :one
SELECT character_id, card_id, hp, atk, tech, init_hp, init_atk, init_tech, max_hp, max_atk, max_tech, special_type
FROM characters
WHERE card_id = $1
`

func (q *Queries) GetCharacterByCardID(ctx context.Context, cardID int32) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacterByCardID, cardID)
	var i Character
	err := row.Scan(
		&i.CharacterID,
		&i.CardID,
		&i.Hp,
		&i.Atk,
		&i.Tech,
		&i.InitHp,
		&i.InitAtk,
		&i.InitTech,
		&i.MaxHp,
		&i.MaxAtk,
		&i.MaxTech,
		&i.SpecialType,
	)
	return i, err
}

const getEquipmentByCardID = `-- name: GetEquipmentByCardID :one
SELECT equipment_id, card_id, bonus_hp, bonus_atk, bonus_tech, init_bonus_hp, init_bonus_atk, init_bonus_tech, max_bonus_hp, max_bonus_atk, max_bonus_tech, buff_effect
FROM equipments
WHERE card_id = $1
`

func (q *Queries) GetEquipmentByCardID(ctx context.Context, cardID int32) (Equipment, error) {
	row := q.db.QueryRowContext(ctx, getEquipmentByCardID, cardID)
	var i Equipment
	err := row.Scan(
		&i.EquipmentID,
		&i.CardID,
		&i.BonusHp,
		&i.BonusAtk,
		&i.BonusTech,
		&i.InitBonusHp,
		&i.InitBonusAtk,
		&i.InitBonusTech,
		&i.MaxBonusHp,
		&i.MaxBonusAtk,
		&i.MaxBonusTech,
		&i.BuffEffect,
	)
	return i, err
}

const getUserCardForUpdate = `-- name: GetUserCardForUpdate :one
SELECT instance_id, user_id, card_id, level
FROM user_cards
WHERE instance_id = $1 AND user_id = $2
FOR UPDATE
`

type GetUserCardForUpdateParams struct {
	InstanceID uuid.UUID
	UserID     uuid.UUID
}

type GetUserCardForUpdateRow struct {
	InstanceID uuid.UUID
	UserID     uuid.UUID
	CardID     int32
	Level      sql.NullInt16
}

func (q *Queries) GetUserCardForUpdate(ctx context.Context, arg GetUserCardForUpdateParams) (GetUserCardForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getUserCardForUpdate, arg.InstanceID, arg.UserID)
	var i GetUserCardForUpdateRow
	err := row.Scan(
		&i.InstanceID,
		&i.UserID,
		&i.CardID,
		&i.Level,
	)
	return i, err
}

const getUserCoinForUpdate = `-- name: GetUserCoinForUpdate :one
SELECT coin
FROM users
WHERE user_id = $1
FOR UPDATE
`

func (q *Queries) GetUserCoinForUpdate(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserCoinForUpdate, userID)
	var coin int32
	err := row.Scan(&coin)
	return coin, err
}

const updateUserCardLevel = `-- name: UpdateUserCardLevel :exec
UPDATE user_cards
SET level = $3
WHERE instance_id = $1 AND user_id = $2
`

type UpdateUserCardLevelParams struct {
	InstanceID uuid.UUID
	UserID     uuid.UUID
	Level      sql.NullInt16
}

func (q *Queries) UpdateUserCardLevel(ctx context.Context, arg UpdateUserCardLevelParams) error {
	_, err := q.db.ExecContext(ctx, updateUserCardLevel, arg.InstanceID, arg.UserID, arg.Level)
	return err
}
