// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gacha.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getRandomCharacterByRarity = `-- name: GetRandomCharacterByRarity :one
SELECT card_id
FROM cards
WHERE card_kind = 1
  AND rarity = $1
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomCharacterByRarity(ctx context.Context, rarity sql.NullString) (int32, error) {
	row := q.db.QueryRowContext(ctx, getRandomCharacterByRarity, rarity)
	var card_id int32
	err := row.Scan(&card_id)
	return card_id, err
}

const getRandomEquipByRarity = `-- name: GetRandomEquipByRarity :one
SELECT card_id
FROM cards
WHERE card_kind = 0
  AND rarity = $1
ORDER BY random()
LIMIT 1
`

func (q *Queries) GetRandomEquipByRarity(ctx context.Context, rarity sql.NullString) (int32, error) {
	row := q.db.QueryRowContext(ctx, getRandomEquipByRarity, rarity)
	var card_id int32
	err := row.Scan(&card_id)
	return card_id, err
}
