// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Card struct {
	CardID      int32
	CardName    string
	CardKind    int16
	CardIconUrl sql.NullString
	Rarity      sql.NullString
	CardDetail  sql.NullString
}

type Character struct {
	CharacterID uuid.UUID
	CardID      int32
	Hp          int32
	Atk         int32
	Tech        int32
	InitHp      int32
	InitAtk     int32
	InitTech    int32
	MaxHp       int32
	MaxAtk      int32
	MaxTech     int32
	SpecialType sql.NullString
}

type Equipment struct {
	EquipmentID   uuid.UUID
	CardID        int32
	BonusHp       int32
	BonusAtk      int32
	BonusTech     int32
	InitBonusHp   int32
	InitBonusAtk  int32
	InitBonusTech int32
	MaxBonusHp    int32
	MaxBonusAtk   int32
	MaxBonusTech  int32
	BuffEffect    sql.NullString
}

type GachaResult struct {
	ResultID   uuid.UUID
	UserID     uuid.UUID
	InstanceID uuid.UUID
	CardID     int32
	Kind       string
	Rarity     string
	IsPickup   bool
	CreatedAt  time.Time
}

type User struct {
	UserID          uuid.UUID
	UserName        string
	IconUrl         sql.NullString
	ProfileMessage  sql.NullString
	BirthMonth      sql.NullInt16
	BirthDay        sql.NullInt16
	LatestLoginDate sql.NullTime
	StreakLoginDays int32
	RegisteredDate  time.Time
	Coin            int32
	GachaStone      int32
	RankPoint       int32
}

type UserCard struct {
	InstanceID   uuid.UUID
	UserID       uuid.UUID
	CardID       int32
	Level        sql.NullInt16
	AcquiredDate time.Time
}
