// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: storage.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const listUserCardDetails = `-- name: ListUserCardDetails :many
SELECT
  uc.instance_id,
  uc.card_id,
  uc.level,

  c.card_name,
  c.card_kind,
  c.rarity,
  c.card_icon_url,

  ch.character_id,
  ch.init_hp        AS ch_init_hp,
  ch.init_atk       AS ch_init_atk,
  ch.init_tech      AS ch_init_tech,
  ch.max_hp         AS ch_max_hp,
  ch.max_atk        AS ch_max_atk,
  ch.max_tech       AS ch_max_tech,
  ch.special_type   AS ch_special_type,

  eq.equipment_id,
  eq.init_bonus_hp   AS eq_init_bonus_hp,
  eq.init_bonus_atk  AS eq_init_bonus_atk,
  eq.init_bonus_tech AS eq_init_bonus_tech,
  eq.max_bonus_hp    AS eq_max_bonus_hp,
  eq.max_bonus_atk   AS eq_max_bonus_atk,
  eq.max_bonus_tech  AS eq_max_bonus_tech,
  eq.buff_effect     AS eq_buff_effect

FROM user_cards uc
JOIN cards c ON c.card_id = uc.card_id
LEFT JOIN characters ch ON ch.card_id = c.card_id
LEFT JOIN equipments eq ON eq.card_id = c.card_id
WHERE uc.user_id = $1
ORDER BY uc.acquired_date DESC
`

type ListUserCardDetailsRow struct {
	InstanceID      uuid.UUID
	CardID          int32
	Level           sql.NullInt16
	CardName        string
	CardKind        int16
	Rarity          sql.NullString
	CardIconUrl     sql.NullString
	CharacterID     uuid.NullUUID
	ChInitHp        sql.NullInt32
	ChInitAtk       sql.NullInt32
	ChInitTech      sql.NullInt32
	ChMaxHp         sql.NullInt32
	ChMaxAtk        sql.NullInt32
	ChMaxTech       sql.NullInt32
	ChSpecialType   sql.NullString
	EquipmentID     uuid.NullUUID
	EqInitBonusHp   sql.NullInt32
	EqInitBonusAtk  sql.NullInt32
	EqInitBonusTech sql.NullInt32
	EqMaxBonusHp    sql.NullInt32
	EqMaxBonusAtk   sql.NullInt32
	EqMaxBonusTech  sql.NullInt32
	EqBuffEffect    sql.NullString
}

func (q *Queries) ListUserCardDetails(ctx context.Context, userID uuid.UUID) ([]ListUserCardDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserCardDetails, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserCardDetailsRow
	for rows.Next() {
		var i ListUserCardDetailsRow
		if err := rows.Scan(
			&i.InstanceID,
			&i.CardID,
			&i.Level,
			&i.CardName,
			&i.CardKind,
			&i.Rarity,
			&i.CardIconUrl,
			&i.CharacterID,
			&i.ChInitHp,
			&i.ChInitAtk,
			&i.ChInitTech,
			&i.ChMaxHp,
			&i.ChMaxAtk,
			&i.ChMaxTech,
			&i.ChSpecialType,
			&i.EquipmentID,
			&i.EqInitBonusHp,
			&i.EqInitBonusAtk,
			&i.EqInitBonusTech,
			&i.EqMaxBonusHp,
			&i.EqMaxBonusAtk,
			&i.EqMaxBonusTech,
			&i.EqBuffEffect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
