// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: storage.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const listUserCardDetails = `-- name: ListUserCardDetails :many
SELECT
  uc.instance_id,

  c.card_id         AS card_id,
  c.card_name       AS card_name,
  c.card_kind       AS card_kind,
  c.rarity          AS rarity,
  c.card_icon_url   AS card_icon_url,

  ch.character_id   AS character_id,
  ch.hp             AS ch_hp,
  ch.atk            AS ch_atk,
  ch.tech           AS ch_tech,
  ch.init_hp        AS ch_init_hp,
  ch.init_atk       AS ch_init_atk,
  ch.init_tech      AS ch_init_tech,
  ch.max_hp         AS ch_max_hp,
  ch.max_atk        AS ch_max_atk,
  ch.max_tech       AS ch_max_tech,
  ch.special_type   AS ch_special_type,

  e.equipment_id    AS equipment_id,
  e.bonus_hp        AS eq_bonus_hp,
  e.bonus_atk       AS eq_bonus_atk,
  e.bonus_tech      AS eq_bonus_tech,
  e.init_bonus_hp   AS eq_init_bonus_hp,
  e.init_bonus_atk  AS eq_init_bonus_atk,
  e.init_bonus_tech AS eq_init_bonus_tech,
  e.max_bonus_hp    AS eq_max_bonus_hp,
  e.max_bonus_atk   AS eq_max_bonus_atk,
  e.max_bonus_tech  AS eq_max_bonus_tech,
  e.buff_effect     AS eq_buff_effect
FROM user_cards uc
JOIN cards c ON c.card_id = uc.card_id
LEFT JOIN characters ch ON ch.card_id = c.card_id
LEFT JOIN equipments e ON e.card_id = c.card_id
WHERE uc.user_id = $1
ORDER BY uc.instance_id DESC
`

type ListUserCardDetailsRow struct {
	InstanceID      uuid.UUID
	CardID          int32
	CardName        string
	CardKind        int16
	Rarity          sql.NullString
	CardIconUrl     sql.NullString
	CharacterID     uuid.NullUUID
	ChHp            sql.NullInt32
	ChAtk           sql.NullInt32
	ChTech          sql.NullInt32
	ChInitHp        sql.NullInt32
	ChInitAtk       sql.NullInt32
	ChInitTech      sql.NullInt32
	ChMaxHp         sql.NullInt32
	ChMaxAtk        sql.NullInt32
	ChMaxTech       sql.NullInt32
	ChSpecialType   sql.NullString
	EquipmentID     uuid.NullUUID
	EqBonusHp       sql.NullInt32
	EqBonusAtk      sql.NullInt32
	EqBonusTech     sql.NullInt32
	EqInitBonusHp   sql.NullInt32
	EqInitBonusAtk  sql.NullInt32
	EqInitBonusTech sql.NullInt32
	EqMaxBonusHp    sql.NullInt32
	EqMaxBonusAtk   sql.NullInt32
	EqMaxBonusTech  sql.NullInt32
	EqBuffEffect    sql.NullString
}

func (q *Queries) ListUserCardDetails(ctx context.Context, userID uuid.UUID) ([]ListUserCardDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserCardDetails, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserCardDetailsRow
	for rows.Next() {
		var i ListUserCardDetailsRow
		if err := rows.Scan(
			&i.InstanceID,
			&i.CardID,
			&i.CardName,
			&i.CardKind,
			&i.Rarity,
			&i.CardIconUrl,
			&i.CharacterID,
			&i.ChHp,
			&i.ChAtk,
			&i.ChTech,
			&i.ChInitHp,
			&i.ChInitAtk,
			&i.ChInitTech,
			&i.ChMaxHp,
			&i.ChMaxAtk,
			&i.ChMaxTech,
			&i.ChSpecialType,
			&i.EquipmentID,
			&i.EqBonusHp,
			&i.EqBonusAtk,
			&i.EqBonusTech,
			&i.EqInitBonusHp,
			&i.EqInitBonusAtk,
			&i.EqInitBonusTech,
			&i.EqMaxBonusHp,
			&i.EqMaxBonusAtk,
			&i.EqMaxBonusTech,
			&i.EqBuffEffect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
