// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_cards.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addUserCard = `-- name: AddUserCard :exec
INSERT INTO user_cards (instance_id, user_id, card_id)
VALUES ($1, $2, $3)
`

type AddUserCardParams struct {
	InstanceID uuid.UUID
	UserID     uuid.UUID
	CardID     int32
}

func (q *Queries) AddUserCard(ctx context.Context, arg AddUserCardParams) error {
	_, err := q.db.ExecContext(ctx, addUserCard, arg.InstanceID, arg.UserID, arg.CardID)
	return err
}

const increaseUserCardLevel = `-- name: IncreaseUserCardLevel :execrows
UPDATE user_cards
SET level = level + 1
WHERE user_id = $1 AND instance_id = $2 AND level < $3
`

type IncreaseUserCardLevelParams struct {
	UserID     uuid.UUID
	InstanceID uuid.UUID
	Level      sql.NullInt16
}

func (q *Queries) IncreaseUserCardLevel(ctx context.Context, arg IncreaseUserCardLevelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, increaseUserCardLevel, arg.UserID, arg.InstanceID, arg.Level)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listUserCards = `-- name: ListUserCards :many
SELECT instance_id, card_id
FROM user_cards
WHERE user_id = $1
ORDER BY acquired_date DESC
`

type ListUserCardsRow struct {
	InstanceID uuid.UUID
	CardID     int32
}

func (q *Queries) ListUserCards(ctx context.Context, userID uuid.UUID) ([]ListUserCardsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserCards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserCardsRow
	for rows.Next() {
		var i ListUserCardsRow
		if err := rows.Scan(&i.InstanceID, &i.CardID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserCard = `-- name: RemoveUserCard :execrows
DELETE FROM user_cards
WHERE user_id = $1 AND instance_id = $2
`

type RemoveUserCardParams struct {
	UserID     uuid.UUID
	InstanceID uuid.UUID
}

func (q *Queries) RemoveUserCard(ctx context.Context, arg RemoveUserCardParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeUserCard, arg.UserID, arg.InstanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
