// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addUserCoin = `-- name: AddUserCoin :one
UPDATE users
SET coin = coin + $1
WHERE user_id = $2
RETURNING coin
`

type AddUserCoinParams struct {
	Amount int32
	UserID uuid.UUID
}

func (q *Queries) AddUserCoin(ctx context.Context, arg AddUserCoinParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, addUserCoin, arg.Amount, arg.UserID)
	var coin int32
	err := row.Scan(&coin)
	return coin, err
}

const addUserGachaStone = `-- name: AddUserGachaStone :one
UPDATE users
SET gacha_stone = gacha_stone + $1
WHERE user_id = $2
RETURNING gacha_stone
`

type AddUserGachaStoneParams struct {
	Amount int32
	UserID uuid.UUID
}

func (q *Queries) AddUserGachaStone(ctx context.Context, arg AddUserGachaStoneParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, addUserGachaStone, arg.Amount, arg.UserID)
	var gacha_stone int32
	err := row.Scan(&gacha_stone)
	return gacha_stone, err
}

const consumeUserCoin = `-- name: ConsumeUserCoin :one
UPDATE users
SET coin = coin - $1
WHERE user_id = $2
  AND coin >= $1
RETURNING coin
`

type ConsumeUserCoinParams struct {
	Amount int32
	UserID uuid.UUID
}

func (q *Queries) ConsumeUserCoin(ctx context.Context, arg ConsumeUserCoinParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, consumeUserCoin, arg.Amount, arg.UserID)
	var coin int32
	err := row.Scan(&coin)
	return coin, err
}

const consumeUserGachaStone = `-- name: ConsumeUserGachaStone :one
UPDATE users
SET gacha_stone = gacha_stone - $1
WHERE user_id = $2
  AND gacha_stone >= $1
RETURNING gacha_stone
`

type ConsumeUserGachaStoneParams struct {
	Amount int32
	UserID uuid.UUID
}

func (q *Queries) ConsumeUserGachaStone(ctx context.Context, arg ConsumeUserGachaStoneParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, consumeUserGachaStone, arg.Amount, arg.UserID)
	var gacha_stone int32
	err := row.Scan(&gacha_stone)
	return gacha_stone, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    user_id, user_name, icon_url, profile_message, birth_month, birth_day, registered_date, latest_login_date, streak_login_days, rank_point, coin, gacha_stone
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,  $10, $11, $12
)
`

type CreateUserParams struct {
	UserID          uuid.UUID
	UserName        string
	IconUrl         sql.NullString
	ProfileMessage  sql.NullString
	BirthMonth      sql.NullInt16
	BirthDay        sql.NullInt16
	RegisteredDate  time.Time
	LatestLoginDate sql.NullTime
	StreakLoginDays int32
	RankPoint       int32
	Coin            int32
	GachaStone      int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.UserID,
		arg.UserName,
		arg.IconUrl,
		arg.ProfileMessage,
		arg.BirthMonth,
		arg.BirthDay,
		arg.RegisteredDate,
		arg.LatestLoginDate,
		arg.StreakLoginDays,
		arg.RankPoint,
		arg.Coin,
		arg.GachaStone,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, userID)
	return err
}

const getUser = `-- name: GetUser :one

SELECT user_id, user_name, icon_url, profile_message, birth_month, birth_day, latest_login_date, streak_login_days, registered_date, coin, gacha_stone, rank_point FROM users
WHERE user_id = $1 LIMIT 1
`

// User系
func (q *Queries) GetUser(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.IconUrl,
		&i.ProfileMessage,
		&i.BirthMonth,
		&i.BirthDay,
		&i.LatestLoginDate,
		&i.StreakLoginDays,
		&i.RegisteredDate,
		&i.Coin,
		&i.GachaStone,
		&i.RankPoint,
	)
	return i, err
}

const updateUserCoin = `-- name: UpdateUserCoin :exec
UPDATE users
SET coin = $1
WHERE user_id = $2
`

type UpdateUserCoinParams struct {
	Coin   int32
	UserID uuid.UUID
}

func (q *Queries) UpdateUserCoin(ctx context.Context, arg UpdateUserCoinParams) error {
	_, err := q.db.ExecContext(ctx, updateUserCoin, arg.Coin, arg.UserID)
	return err
}

const updateUserGachaStone = `-- name: UpdateUserGachaStone :exec
UPDATE users
SET gacha_stone = $1
WHERE user_id = $2
`

type UpdateUserGachaStoneParams struct {
	GachaStone int32
	UserID     uuid.UUID
}

func (q *Queries) UpdateUserGachaStone(ctx context.Context, arg UpdateUserGachaStoneParams) error {
	_, err := q.db.ExecContext(ctx, updateUserGachaStone, arg.GachaStone, arg.UserID)
	return err
}

const updateUserRankPoint = `-- name: UpdateUserRankPoint :exec
UPDATE users
SET rank_point = $1
WHERE user_id = $2
`

type UpdateUserRankPointParams struct {
	RankPoint int32
	UserID    uuid.UUID
}

func (q *Queries) UpdateUserRankPoint(ctx context.Context, arg UpdateUserRankPointParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRankPoint, arg.RankPoint, arg.UserID)
	return err
}
